org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=1.20.1
loader_version=0.16.0
parchment_mappings_version = 2023.09.03

mod_version=0.1.1
group=moe.mutsuk1
archives_base_name=BetterSpellbook
modID=betterspellbook
mod_name=BetterSpellbook

#dep
serialization_hooks_version=0.4.99999
hexcasting_version=0.11.2-pre-702
paucal_version=0.6.0-pre-118
inline_version=1.0.1
patchouli_version=85
cloth_config_version=11.1.136
fabric_api_version = 0.85.0+1.20.1
cca_version=5.2.2